version: '3.8'

services:
  word-mcp-server:
    build: .
    container_name: word-mcp-server
    restart: unless-stopped
    
    # Environment variables for MCP HTTP transport
    environment:
      - MCP_TRANSPORT=streamable-http
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8000
      - MCP_PATH=/mcp
      - FASTMCP_LOG_LEVEL=INFO
      - PYTHONPATH=/app
    
    # Port mapping
    ports:
      - "8000:8000"
    
    # Volume for persistent document storage
    volumes:
      - word_documents:/app/documents
      - word_temp:/app/temp
    
    # Health check - use curl to check HTTP endpoint
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Security options
    security_opt:
      - no-new-privileges:true
    read_only: false  # Word documents need write access
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Named volumes for data persistence
volumes:
  word_documents:
    driver: local
  word_temp:
    driver: local

# Networks (optional for Coolify isolation)
networks:
  default:
    name: word-mcp-network