# Nixpacks configuration for Word MCP Server
providers = ["python"]

[phases.setup]
nixPkgs = ["libreoffice", "python311", "python311Packages.pip"]

[start]
cmd = "word_mcp_server"

[variables]
MCP_TRANSPORT = "streamable-http"
MCP_HOST = "0.0.0.0"
MCP_PORT = "8000"
MCP_PATH = "/mcp"
FASTMCP_LOG_LEVEL = "INFO"